// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands.proto

package commands

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{0}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ErrorReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorReply) Reset()         { *m = ErrorReply{} }
func (m *ErrorReply) String() string { return proto.CompactTextString(m) }
func (*ErrorReply) ProtoMessage()    {}
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{1}
}
func (m *ErrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorReply.Unmarshal(m, b)
}
func (m *ErrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorReply.Marshal(b, m, deterministic)
}
func (dst *ErrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorReply.Merge(dst, src)
}
func (m *ErrorReply) XXX_Size() int {
	return xxx_messageInfo_ErrorReply.Size(m)
}
func (m *ErrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorReply proto.InternalMessageInfo

func (m *ErrorReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ErrorReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListReply struct {
	Data                 []*List     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                *ErrorReply `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{2}
}
func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (dst *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(dst, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetData() []*List {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListReply) GetError() *ErrorReply {
	if m != nil {
		return m.Error
	}
	return nil
}

type List struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{3}
}
func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (dst *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(dst, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *List) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *List) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type GetRequest struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	InstallDependencies  bool     `protobuf:"varint,2,opt,name=install_dependencies,json=installDependencies,proto3" json:"install_dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{4}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *GetRequest) GetInstallDependencies() bool {
	if m != nil {
		return m.InstallDependencies
	}
	return false
}

type RemoveRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{5}
}
func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(dst, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnableRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableRequest) Reset()         { *m = EnableRequest{} }
func (m *EnableRequest) String() string { return proto.CompactTextString(m) }
func (*EnableRequest) ProtoMessage()    {}
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{6}
}
func (m *EnableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableRequest.Unmarshal(m, b)
}
func (m *EnableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableRequest.Marshal(b, m, deterministic)
}
func (dst *EnableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableRequest.Merge(dst, src)
}
func (m *EnableRequest) XXX_Size() int {
	return xxx_messageInfo_EnableRequest.Size(m)
}
func (m *EnableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableRequest proto.InternalMessageInfo

func (m *EnableRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *EnableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DisableRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableRequest) Reset()         { *m = DisableRequest{} }
func (m *DisableRequest) String() string { return proto.CompactTextString(m) }
func (*DisableRequest) ProtoMessage()    {}
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{7}
}
func (m *DisableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRequest.Unmarshal(m, b)
}
func (m *DisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRequest.Marshal(b, m, deterministic)
}
func (dst *DisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRequest.Merge(dst, src)
}
func (m *DisableRequest) XXX_Size() int {
	return xxx_messageInfo_DisableRequest.Size(m)
}
func (m *DisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRequest proto.InternalMessageInfo

func (m *DisableRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DisableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UploadRequest struct {
	Pem                  []byte   `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{8}
}
func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (dst *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(dst, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetPem() []byte {
	if m != nil {
		return m.Pem
	}
	return nil
}

func (m *UploadRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type UploadCertsRequest struct {
	Pem                  []byte   `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadCertsRequest) Reset()         { *m = UploadCertsRequest{} }
func (m *UploadCertsRequest) String() string { return proto.CompactTextString(m) }
func (*UploadCertsRequest) ProtoMessage()    {}
func (*UploadCertsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_9840b70ca25b4425, []int{9}
}
func (m *UploadCertsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadCertsRequest.Unmarshal(m, b)
}
func (m *UploadCertsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadCertsRequest.Marshal(b, m, deterministic)
}
func (dst *UploadCertsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadCertsRequest.Merge(dst, src)
}
func (m *UploadCertsRequest) XXX_Size() int {
	return xxx_messageInfo_UploadCertsRequest.Size(m)
}
func (m *UploadCertsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadCertsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadCertsRequest proto.InternalMessageInfo

func (m *UploadCertsRequest) GetPem() []byte {
	if m != nil {
		return m.Pem
	}
	return nil
}

func (m *UploadCertsRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "commands.ListRequest")
	proto.RegisterType((*ErrorReply)(nil), "commands.ErrorReply")
	proto.RegisterType((*ListReply)(nil), "commands.ListReply")
	proto.RegisterType((*List)(nil), "commands.List")
	proto.RegisterType((*GetRequest)(nil), "commands.GetRequest")
	proto.RegisterType((*RemoveRequest)(nil), "commands.RemoveRequest")
	proto.RegisterType((*EnableRequest)(nil), "commands.EnableRequest")
	proto.RegisterType((*DisableRequest)(nil), "commands.DisableRequest")
	proto.RegisterType((*UploadRequest)(nil), "commands.UploadRequest")
	proto.RegisterType((*UploadCertsRequest)(nil), "commands.UploadCertsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandsClient is the client API for Commands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandsClient interface {
	ListCommand(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	GetCommand(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ErrorReply, error)
	RemoveCommand(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*ErrorReply, error)
	EnableCommand(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*ErrorReply, error)
	DisableCommand(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*ErrorReply, error)
	UploadCommand(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*ErrorReply, error)
	UploadCertsCommand(ctx context.Context, in *UploadCertsRequest, opts ...grpc.CallOption) (*ErrorReply, error)
}

type commandsClient struct {
	cc *grpc.ClientConn
}

func NewCommandsClient(cc *grpc.ClientConn) CommandsClient {
	return &commandsClient{cc}
}

func (c *commandsClient) ListCommand(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/ListCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) GetCommand(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ErrorReply, error) {
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/GetCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) RemoveCommand(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*ErrorReply, error) {
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/RemoveCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) EnableCommand(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*ErrorReply, error) {
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/EnableCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) DisableCommand(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*ErrorReply, error) {
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/DisableCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) UploadCommand(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*ErrorReply, error) {
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/UploadCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) UploadCertsCommand(ctx context.Context, in *UploadCertsRequest, opts ...grpc.CallOption) (*ErrorReply, error) {
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, "/commands.Commands/UploadCertsCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandsServer is the server API for Commands service.
type CommandsServer interface {
	ListCommand(context.Context, *ListRequest) (*ListReply, error)
	GetCommand(context.Context, *GetRequest) (*ErrorReply, error)
	RemoveCommand(context.Context, *RemoveRequest) (*ErrorReply, error)
	EnableCommand(context.Context, *EnableRequest) (*ErrorReply, error)
	DisableCommand(context.Context, *DisableRequest) (*ErrorReply, error)
	UploadCommand(context.Context, *UploadRequest) (*ErrorReply, error)
	UploadCertsCommand(context.Context, *UploadCertsRequest) (*ErrorReply, error)
}

func RegisterCommandsServer(s *grpc.Server, srv CommandsServer) {
	s.RegisterService(&_Commands_serviceDesc, srv)
}

func _Commands_ListCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).ListCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/ListCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).ListCommand(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_GetCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).GetCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/GetCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).GetCommand(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_RemoveCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).RemoveCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/RemoveCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).RemoveCommand(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_EnableCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).EnableCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/EnableCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).EnableCommand(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_DisableCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).DisableCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/DisableCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).DisableCommand(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_UploadCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).UploadCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/UploadCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).UploadCommand(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_UploadCertsCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).UploadCertsCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commands.Commands/UploadCertsCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).UploadCertsCommand(ctx, req.(*UploadCertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commands_serviceDesc = grpc.ServiceDesc{
	ServiceName: "commands.Commands",
	HandlerType: (*CommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCommand",
			Handler:    _Commands_ListCommand_Handler,
		},
		{
			MethodName: "GetCommand",
			Handler:    _Commands_GetCommand_Handler,
		},
		{
			MethodName: "RemoveCommand",
			Handler:    _Commands_RemoveCommand_Handler,
		},
		{
			MethodName: "EnableCommand",
			Handler:    _Commands_EnableCommand_Handler,
		},
		{
			MethodName: "DisableCommand",
			Handler:    _Commands_DisableCommand_Handler,
		},
		{
			MethodName: "UploadCommand",
			Handler:    _Commands_UploadCommand_Handler,
		},
		{
			MethodName: "UploadCertsCommand",
			Handler:    _Commands_UploadCertsCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commands.proto",
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor_commands_9840b70ca25b4425) }

var fileDescriptor_commands_9840b70ca25b4425 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x4d, 0xeb, 0xd3, 0x40,
	0x10, 0xc6, 0xff, 0x31, 0xb5, 0x24, 0xd3, 0x17, 0x64, 0x5b, 0x35, 0x94, 0x1e, 0xca, 0x9e, 0x8a,
	0x87, 0x82, 0xed, 0x45, 0xea, 0x45, 0x6d, 0x8b, 0x20, 0x1e, 0x74, 0xc1, 0x93, 0x07, 0xd9, 0x36,
	0x03, 0x06, 0xf3, 0x66, 0x76, 0x23, 0xf4, 0xa3, 0xfa, 0x6d, 0x64, 0x37, 0xbb, 0x26, 0xe9, 0xbf,
	0x2d, 0x94, 0xde, 0x66, 0x66, 0xe7, 0xf9, 0xf1, 0xa4, 0xcf, 0x50, 0x18, 0x1e, 0xb2, 0x24, 0xe1,
	0x69, 0x28, 0x16, 0x79, 0x91, 0xc9, 0x8c, 0x78, 0xb6, 0xa7, 0x03, 0xe8, 0x7d, 0x8e, 0x84, 0x64,
	0xf8, 0xbb, 0x44, 0x21, 0xe9, 0x1a, 0x60, 0x57, 0x14, 0x59, 0xc1, 0x30, 0x8f, 0x8f, 0xe4, 0x05,
	0x74, 0x85, 0xe4, 0xb2, 0x14, 0x81, 0x33, 0x73, 0xe6, 0x1e, 0x33, 0x1d, 0x19, 0xc3, 0x53, 0x54,
	0x5b, 0xc1, 0x93, 0x99, 0x33, 0xf7, 0x59, 0xd5, 0xd0, 0xef, 0xe0, 0x57, 0x28, 0x25, 0xa5, 0xd0,
	0x09, 0xb9, 0xe4, 0x81, 0x33, 0x73, 0xe7, 0xbd, 0xe5, 0x70, 0xf1, 0xdf, 0x80, 0x5e, 0xd1, 0x6f,
	0xe4, 0x55, 0x13, 0xd3, 0x5b, 0x8e, 0xeb, 0xa5, 0xda, 0x83, 0x85, 0x7f, 0x81, 0x8e, 0x52, 0x92,
	0x29, 0xf8, 0x29, 0x4f, 0x50, 0xe4, 0xfc, 0x80, 0xda, 0x95, 0xcf, 0xea, 0x01, 0x21, 0xd0, 0x51,
	0x8d, 0xf1, 0xa5, 0x6b, 0xf5, 0x11, 0xbc, 0x94, 0x3f, 0xb3, 0x22, 0x70, 0xf5, 0xd4, 0x74, 0xf4,
	0x2b, 0xc0, 0x47, 0xb4, 0x1f, 0x4e, 0x9e, 0x81, 0x5b, 0x16, 0x91, 0x21, 0xaa, 0x92, 0xbc, 0x86,
	0x71, 0x94, 0x0a, 0xc9, 0xe3, 0xf8, 0x47, 0x88, 0x39, 0xa6, 0x21, 0xa6, 0x87, 0x08, 0x85, 0x66,
	0x7b, 0x6c, 0x64, 0xde, 0xb6, 0x8d, 0x27, 0xfa, 0x1e, 0x06, 0x0c, 0x93, 0xec, 0x0f, 0x5a, 0xea,
	0xcd, 0x6e, 0x15, 0x62, 0x97, 0xf2, 0x7d, 0x7c, 0x07, 0xe2, 0x03, 0x0c, 0xb7, 0x91, 0xb8, 0x8f,
	0xb1, 0x82, 0xc1, 0xb7, 0x3c, 0xce, 0x78, 0xd8, 0xf8, 0x7d, 0x72, 0x4c, 0xb4, 0xb8, 0xcf, 0x54,
	0xa9, 0x26, 0xbf, 0xf0, 0xa8, 0x55, 0x7d, 0xa6, 0x4a, 0xfa, 0x06, 0x48, 0x25, 0xda, 0x60, 0x21,
	0xc5, 0x0d, 0xca, 0xe5, 0x5f, 0x17, 0xbc, 0x8d, 0x09, 0x9f, 0xbc, 0xad, 0x4e, 0xd2, 0xf4, 0xe4,
	0xf9, 0xc9, 0xed, 0x54, 0xd8, 0xc9, 0xe8, 0x74, 0x9c, 0xc7, 0x47, 0xfa, 0x40, 0xd6, 0x3a, 0x55,
	0xab, 0x6d, 0x9c, 0x54, 0x9d, 0xf5, 0xe4, 0xec, 0xa1, 0xd1, 0x07, 0xf2, 0xce, 0xc6, 0x67, 0xe5,
	0x2f, 0xeb, 0xc5, 0x56, 0xae, 0xd7, 0x08, 0x55, 0x7a, 0x67, 0x08, 0xad, 0x58, 0x2f, 0x12, 0xea,
	0xf0, 0x2c, 0x22, 0xa8, 0x37, 0xdb, 0xb1, 0x5e, 0x73, 0x61, 0x72, 0x78, 0xec, 0xa2, 0x95, 0xea,
	0x45, 0xc2, 0xa7, 0x56, 0x92, 0x16, 0x33, 0x3d, 0xc5, 0x34, 0x73, 0xbe, 0xc4, 0xda, 0x77, 0xf5,
	0x5f, 0xce, 0xea, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x03, 0x1d, 0xa3, 0x84, 0x04, 0x00,
	0x00,
}
